import React, { useState } from 'react';
import { useToast } from '../../context/ToastContext';
import { LocationPriorityRank, ResourceItem, ShelterItem, AlertItem } from '../../types';
import { FileText, Copy, Check, Printer, X, ShieldAlert } from 'lucide-react';

interface SitRepModalProps {
  isOpen: boolean;
  onClose: () => void;
  ranking: LocationPriorityRank[];
  resources: ResourceItem[];
  shelters: ShelterItem[];
  alerts: AlertItem[];
  district: string;
}

export const SitRepModal: React.FC<SitRepModalProps> = ({
  isOpen,
  onClose,
  ranking,
  resources,
  shelters,
  alerts,
  district,
}) => {
  const { showToast } = useToast();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const top = ranking[0];
  const criticalCount = ranking.filter((r) => r.flood_risk_pct >= 80).length;
  const highCount = ranking.filter((r) => r.flood_risk_pct >= 60 && r.flood_risk_pct < 80).length;
  const totalExposed = ranking.reduce((s, r) => s + r.estimated_exposed_population, 0);

  const boatResources = resources.filter((r) => r.resource_type.toLowerCase().includes('boat'));
  const totalAvailBoats = boatResources.reduce((s, r) => s + r.available_quantity, 0);
  const totalDeployedBoats = boatResources.reduce((s, r) => s + r.deployed_quantity, 0);

  const nowStr = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const sitRepMarkdown = `# BIHAR DISASTER MANAGEMENT AUTHORITY (BSDMA)
## FLOOD EMERGENCY SITUATION REPORT (SITREP) - BRIEFING
**Date & Time**: ${nowStr} IST
**Operational Jurisdiction**: ${district === 'ALL' ? 'Statewide (All Bihar River Basins)' : `${district} District`}
**Intelligence Status**: REAL-TIME EVIDENCE-BASED TRIAGE

---

### 1. OPERATIONAL SUMMARY
- **Priority #1 Critical Hotspot**: ${top ? `${top.location_name} (${top.district} District)` : 'N/A'}
- **Surge Rate at Top Sector**: ${top ? `+${top.river_rise_rate_3h_m}m / 3h` : 'N/A'}
- **Locations at Critical Risk (≥80%)**: ${criticalCount}
- **Locations at High Risk (60-79%)**: ${highCount}
- **Total Population in Hazard Zones**: ~${totalExposed.toLocaleString()} people

### 2. PRIORITY HOTSPOTS ORDER OF ATTENTION
${ranking.slice(0, 5).map((r) => `${r.rank}. **${r.location_name}** (${r.district})
   - Priority Score: ${r.priority_score.toFixed(1)} / 100
   - Flood Risk: ${r.flood_risk_pct.toFixed(1)}% | Road Status: ${r.road_accessibility_status}
   - Key Drivers: ${r.key_drivers.join('; ')}`).join('\n\n')}

### 3. FRONTLINE RESOURCE BALANCE
- **Rescue Boats Available**: ${totalAvailBoats} units
- **Rescue Boats Deployed**: ${totalDeployedBoats} units
- **Critical Sector Boat Shortage**: ${top ? Math.max(0, Math.ceil(top.estimated_exposed_population * 0.3 / 40) - totalAvailBoats) : 0} units

### 4. ACTIVE EMERGENCY BROADCASTS (${alerts.length})
${alerts.slice(0, 3).map((a) => `- [${a.severity}] ${a.title}: ${a.what_happened}`).join('\n')}

---
*Generated by JalRakshak Bihar AI Decision-Support Platform*`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sitRepMarkdown);
    setCopied(true);
    showToast({
      type: 'success',
      title: 'SitRep Copied to Clipboard',
      message: 'Operational briefing formatted in Markdown for immediate sharing.',
    });
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content"
        style={{ maxWidth: '780px' }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <div
              style={{
                background: 'rgba(56, 189, 248, 0.15)',
                padding: '0.5rem',
                borderRadius: '8px',
                color: '#38bdf8',
                border: '1px solid rgba(56, 189, 248, 0.3)',
              }}
            >
              <FileText size={20} />
            </div>
            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--text-main)' }}>
                Official Situation Report (SitRep)
              </h3>
              <p style={{ fontSize: '0.74rem', color: 'var(--text-muted)' }}>
                Instant operational briefing for Disaster Management Commissioner & Cabinet
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'transparent',
              border: 'none',
              color: 'var(--text-muted)',
              cursor: 'pointer',
            }}
          >
            <X size={20} />
          </button>
        </div>

        <div className="modal-body">
          <div
            style={{
              background: 'rgba(10, 15, 29, 0.9)',
              border: '1px solid var(--border-subtle)',
              borderRadius: '10px',
              padding: '1.25rem',
              fontFamily: 'var(--font-mono)',
              fontSize: '0.8rem',
              color: '#cbd5e1',
              whiteSpace: 'pre-wrap',
              maxHeight: '450px',
              overflowY: 'auto',
              lineHeight: 1.6,
            }}
          >
            {sitRepMarkdown}
          </div>
        </div>

        <div className="modal-footer">
          <button type="button" className="btn btn-secondary" onClick={handlePrint}>
            <Printer size={15} />
            <span>Print / PDF</span>
          </button>
          <button type="button" className="btn btn-primary" onClick={handleCopy}>
            {copied ? <Check size={15} /> : <Copy size={15} />}
            <span>{copied ? 'Copied!' : 'Copy SitRep Markdown'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
